name: Download JESI Growth Data

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  download-growth-data:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Growth data
        run: |
          PYTHONPATH=. python scripts/01_download_growth_data.py

      - name: Display downloaded data
        run: |
          echo "Downloaded file:"
          ls -lh data/raw/

          echo
          echo "First rows:"
          head -20 data/raw/growth_indicators_2015_2025.csv

      - name: Upload Growth dataset
        uses: actions/upload-artifact@v4
        with:
          name: jesI-growth-data-2015-2025
          path: data/raw/growth_indicators_2015_2025.csv
